version: '3'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx/conf.d
      - ./rapidpro/sitestatic:/django_static
      - ./rapidpro/media:/django_media
    ports:
      - "8090:80"
    depends_on:
      - rapidpro
      - courier
  rapidpro:
    build: rapidpro
    depends_on:
      - redis
      - postgresql
    expose:
      - "8000"
    environment:
      - ELASTICSEARCH_URL=elasticsearch
    volumes:
      - ./rapidpro:/code
    entrypoint: /code/entrypoint.sh
    working_dir: /code
  celery_base:
    build: rapidpro
    working_dir: /code
    volumes:
      - ./rapidpro:/code
    depends_on:
      - rapidpro
    command: ["celery", "--beat", "--app=temba", "worker", "--loglevel=DEBUG", "--queues=celery,flows"]
  celery_msgs:
    build: rapidpro
    working_dir: /code
    volumes:
      - ./rapidpro:/code
    depends_on:
      - rapidpro
    command: ["celery", "--beat", "--app=temba", "worker", "--loglevel=DEBUG", "--queues=msgs,handler"]
  redis:
    image: redis:alpine
    environment:
      - LOGLEVEL=debug
  postgresql:
    image: mdillon/postgis
    restart: always
    environment:
      - POSTGRES_USER=rapidpro
      - POSTGRES_PASS=rapidpro
      - POSTGRES_DBNAME=rapidpro
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - 5434:5432
  courier:
    build: courier
    depends_on:
      - rapidpro
    links:
      - redis
      - postgresql
    environment:
      - COURIER_DOMAIN=97967cab.ngrok.io
      - COURIER_SPOOL_DIR=/tmp/courier/
      - COURIER_DB=postgres://rapidpro:rapidpro@postgresql/rapidpro?sslmode=disable
      - COURIER_REDIS=redis://redis:6379/15
      - COURIER_PORT=8080
      - COURIER_LOG_LEVEL=DEBUG
    expose:
      - "8081"
  elasticsearch:
    image: elasticsearch:6.8.0
  indexer:
    build: rp-indexer
    links:
      - elasticsearch
    environment:
      - INDEXER_DB=postgres://rapidpro:rapidpro@postgresql/rapidpro?sslmode=disable
      - INDEXER_ELASTIC_URL=http://elasticsearch:9200
